// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxkW1mlvK1WUoiumI7xkndNrzwOlBKTE',
    appId: '1:690061509723:web:e7eb6fbba317f8df342b7e',
    messagingSenderId: '690061509723',
    projectId: 'home-automation-8a73d',
    authDomain: 'home-automation-8a73d.firebaseapp.com',
    storageBucket: 'home-automation-8a73d.appspot.com',
    measurementId: 'G-ZVJJ1HJENE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4HNaVHA-DAGRidwm8DfPYejEFK7eqF-E',
    appId: '1:690061509723:android:d93d93c082161ef3342b7e',
    messagingSenderId: '690061509723',
    projectId: 'home-automation-8a73d',
    storageBucket: 'home-automation-8a73d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkdBm3deoGFaaOkiMz5n3Ezl2PK2zBt5M',
    appId: '1:690061509723:ios:ff12d55709af31d3342b7e',
    messagingSenderId: '690061509723',
    projectId: 'home-automation-8a73d',
    storageBucket: 'home-automation-8a73d.appspot.com',
    iosBundleId: 'com.example.homeAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkdBm3deoGFaaOkiMz5n3Ezl2PK2zBt5M',
    appId: '1:690061509723:ios:ff12d55709af31d3342b7e',
    messagingSenderId: '690061509723',
    projectId: 'home-automation-8a73d',
    storageBucket: 'home-automation-8a73d.appspot.com',
    iosBundleId: 'com.example.homeAutomation',
  );
}
